SET DATABASE COLLATION "German"
CREATE SCHEMA PUBLIC AUTHORIZATION DBA
CREATE CACHED TABLE "Tabelle1"("ID" NUMERIC(100) NOT NULL PRIMARY KEY,"Vorname" VARCHAR(100),"Nachname" VARCHAR(100))
CREATE USER SA PASSWORD ""
GRANT DBA TO SA
SET WRITE_DELAY 60
SET SCHEMA PUBLIC
INSERT INTO "Tabelle1" VALUES(1,'Max','Mustermann')
INSERT INTO "Tabelle1" VALUES(2,'Maximiliane','Musterfrau')
